apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swagger-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: swagger-demo
    spec:
      containers:
        - name: swagger-demo
          image: 'gcr.io/spring-boot-swagger/spring-boot-swagger:v1'
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: swagger-demo-service
  labels:
    name: swagger-demo-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: swagger-demo
  type: LoadBalancer